name: scsmm
description: SCS Mods Manager, a simple CLI to manager environments in your game directory.
version: 0.0.3
homepage: https://github.com/tihrasguinho/scsmm

executables:
  scsmm: scsmm.dart

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  ffi: ^2.1.4
  path: ^1.9.0
  win32: ^5.14.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
