name: scsmm
description: SCS Mods Manager, a simple CLI to manager environments in your game directory.
version: 0.0.1
homepage: https://github.com/tihrasguinho/scsmm

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
